### ISSUE TITLE
Request: documentation on running a version on one's own server

### ISSUE THREAD

**Issue by liamtimms** [epam/mriviewer#46]
Hi, 

I am interested in using your work but I can't find documentation for actually building, running and serving the application. My use case would be to share an interactive visualization with collaborators without needing to send them a file directly. Is there a simple `npm` command to install and run an instance? 

Thank you.

**Comment by alterfo** [comment]
@liamtimms, hello!

Thank you for a very good question!

Currently the simplest way is to run in the folder with downloaded source code:
```
$ npm i
$ npm i -g serve
$ npm build
$ serve ./build
```
, assuming that you have Node.js installed. 

If you have Docker in your system as well, you can try to run the following command:
`npm run build && docker run --name med3web -v ./build:/usr/share/nginx/html:ro -d -p 8080:80 nginx` because we have Dockerfile included. The application will be run on `http://localhost:8080`.

Please, bear with us - in next releases we are going to introduce other options. Let us know if you have particular needs and technological restrictions/frameworks.

PS: sorry for prematurely notice, we also have a pretty nifty feature, but there are issues (CORS- and redirect-related): you can try to put your DICOM file somewhere in the Web with public access and put the link to it as a parameter to the url (e.g. https://your.domain?url=https://url.to/file_list.txt)
